services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: livebridge-mediamtx
    restart: unless-stopped
    environment:
      - MTX_WEBRTCADDITIONALHOSTS=212.85.1.54
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
    ports:
      - "1935:1935"     # RTMP
      - "8189:8189/udp" # WebRTC mídia UDP
      - "8189:8189/tcp" # WebRTC fallback TCP (quando UDP bloqueado)
      - "8888:8888"     # HLS
      - "8889:8889"     # WebRTC HTTP

  nginx:
    image: nginx:alpine
    container_name: livebridge-player
    restart: unless-stopped
    volumes:
      - ./player:/usr/share/nginx/html:ro
      - ./player/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
